steps:

  - name: ":terraform: Running terraform plan"
    branches: "!main"
    command: ./auto/plan
    agents:
      queue: default

  - wait

  - name: ":terraform: Deploy to prod"
    branches: "!main"
    command: ./auto/apply
    agents:
      queue: default
