steps:

  - name: ":terraform: Running terraform plan"
    command: ./auto/terraform-plan
    agents:
      queue: default

  - wait

  - name: ":terraform: Deploy to prod"
    command: ./auto/terraform-apply
    agents:
      queue: default

  - name: :terraform: Destroy build on demand"
    command: ./auto/terraform-destroy
    agents:
      queue: default
    if: |
      build.mesage == "Destroy Vault Infrastructure"
      build.branch == "main"