steps:

  - name: ":terraform: Running terraform plan"
    command: ./auto/terraform-plan
    agents:
      queue: default

  - block: ":rocket: Deploy to PROD?"
    branches: main

  - name: ":terraform: Deploy to prod"
    command: ./auto/terraform-apply
    agents:
      queue: default
      
  - block: ":skull_and_crossbones: Destroy Infrastructure?"
    branches: main

  - name: ":terraform: Destroy build on demand"
    command: ./auto/terraform-destroy
    agents:
      queue: default