steps:

  - name: ":terraform: Running terraform plan"
    command: ./auto/terraform-plan
    agents:
      queue: default

  - block: ":rocket: Deploy to PROD?"
    branches: main

  - name: ":terraform: Deploy to prod"
    command: ./auto/terraform-apply
    agents:
      queue: default
      
  - block: ":rocket: Destroy Infrastructure? "
    branches: master
  - name: :terraform: Destroy build on demand"
    command: ./auto/terraform-destroy
    agents:
      queue: default