steps:

  - name: "Running terraform plan"
    command: ./auto/plan
    agents:
      queue: default

  - wait

  - name: "Deploy to prod"
    branches: "!main"
    command: ./auto/apply
    agents:
      queue: default
